### ISSUE TITLE
Menu: Services, analog & bluetooth

### ISSUE THREAD

**Issue by AxiomSteve** [ColquhounAudio/AxiomBuild#16]
The "Services" tab in the menu does not appear to have any function. Remove?

**Comment by AxiomSteve** [comment]
We should also remove the analog input and bluetooth checkboxes until they are functional.

**Comment by IanColquhoun** [comment]
At this point we should proceed to have three functional buttons in the drop-down: Analog, Optical, and Bluetooth.  Do we need another LED for Bluetooth or could it be just "no LED" or "2 x LED"?
