### ISSUE TITLE
Spotify inconsistent availability

### ISSUE THREAD

**Issue by AxiomSteve** [ColquhounAudio/AxiomBuild#3]
Spotify does not always show as an available device, or disappears during playback.

**Comment by ggiraudon** [comment]
Problem should be resolved in latest updates of Volumio2 Master branch.
Tested from Windows Spotify client and have not lost visibility yet.

**Comment by andrew-axiom** [comment]
I tried Spotify on this latest image and my device mow appears as AxiomAir-default, not the actual name I gave my system. It was working correctly with the last image.

**Comment by ggiraudon** [comment]
Can you do me a favor and try rebooting ?
I want to know if that sets the machine name properly.

**Comment by andrew-axiom** [comment]
Changed name under System Settings, rebooted, system is correctly renamed but showing up as AxiomAir-default in Spotify. Rebooted a second time and now the new system name is showing up correctly on Spotify.

**Comment by AxiomSteve** [comment]
Name updates correctly
