### ISSUE TITLE
Battery monitoring needs to be tested

### ISSUE THREAD

**Issue by andrew-axiom** [ColquhounAudio/AxiomBuild#37]
Battery monitoring functions not working.

When Pi GPIO17 goes high, battery warning LED should be illuminated solid (Red LED, GPB4 on MCP23017).

When Pi GPIO22 goes high, normal system shutdown routine should be initiated.

**Comment by IanColquhoun** [comment]
What everyone would actually like is a battery fuel level in the UI.  Is this possible?

**Comment by andrew-axiom** [comment]
> What everyone would actually like is a battery fuel level in the UI. Is this possible?

Not with the current hardware as we only have two control signals going to the Pi, one voltage sets the warning light, the other initiates shutdown. So we are only monitoring for two voltage levels.

**Comment by andrew-axiom** [comment]
I am trying to test battery monitoring on the N2 hardware and found that the battery functions are no longer working on V2.10.3. This is a major issue as it will impact battery life for anyone who has updated in the field. SD card corruption is also a risk as power will suddenly be cut when the internal battery pack protection mechanism kicks in.

**Comment by IanColquhoun** [comment]
Moved to required for next Update
