### ISSUE TITLE
No Network Status

### ISSUE THREAD

**Issue by andrew-axiom** [ColquhounAudio/AxiomBuild#4]
Network Status on Network Settings page of the UI displays no information.

**Comment by ggiraudon** [comment]
Problem was found in the parsing library used by Volumio that handles interface information.
It is deprecated and I have updated it to match the new ifconfig format.
Fix is in the master branch of Volumio2 and will be part of new image

**Comment by andrew-axiom** [comment]
Network Status is now being displayed correctly.
