### ISSUE TITLE
BryFi v2 Bugs

### ISSUE THREAD

**Issue by IanColquhoun** [ColquhounAudio/AxiomBuild#40]
- Hotspot name shows as AxiomAir-xxxxxx
- Will not go on a Network from the Hotspot, WAC works though and it shows as a BryFi in WAC
- Remove the background in the Appearance tab that says AxiomAir

**Comment by ggiraudon** [comment]
This was solved in v2.09.1 in image https://s3.amazonaws.com/axiom-air-install-files/BryFiV2/BryFiV2-V2.09.1-2019-01-08-pi.img.zip
