### ISSUE TITLE
Device Name Change

### ISSUE THREAD

**Issue by andrew-axiom** [ColquhounAudio/AxiomBuild#5]
If the device name is changed during WAC setup, the new name will appear in both Airplay/iTunes and the UI. However, if the name is changed under System Settings on the UI, the new name is not reflected in Airplay/iTunes.

**Comment by ggiraudon** [comment]
Will investigate further. Issue is deeper than it looks because files are created all over the place by Volumio with the device name. Its a bit of a mess.

**Comment by AxiomSteve** [comment]
This is still an issue

**Comment by AxiomSteve** [comment]
This is now updating correctly
