### ISSUE TITLE
Input switching order incorrect

### ISSUE THREAD

**Issue by andrew-axiom** [ColquhounAudio/AxiomBuild#8]
This is a holdover from something that Mike said was going to be "complicated" to fix. The order of the input switching should be WiFi(Pi) - Analogue - Optical - Wifi(Pi) - etc. It is currently backwards: WiFi(Pi) - Optical - Analogue - WiFi(Pi).

**Comment by ggiraudon** [comment]
I just slapped a tentative patch in the Volumio2 Master and it "seems" to work but I may be very wrong on this.
Please test it on the next image and let me know what happens.

**Comment by andrew-axiom** [comment]
Unfortunately this is not working. First button press switches the input to analogue, but both WiFi/Pi and Analogue indicator LEDs are lit. Pressing the button again keeps the Analogue input on but turns Optical on at the same time = bad. Analogue and Optical indicator LEDs are both lit. Pressing again returns correctly to the WiFi/Pi with only the WiFi/Pi indicator LED lit.
